Preliminary F3DEX3 LVP support
gonetz/GLideN64 pull request #2842
Opened 2024-06-07 13:02 UTC by aglab2

This PR provides a preliminary support for [F3DEX3](https://github.com/HackerN64/F3DEX3/). Most of the work done here is chore to make sure F3DEX3 games boot while looking correctly with unaltered F3DEX2 display lists.

2024-06-07 14:23 UTC, weinerschnitzel commented
Can't wait to see the sauraen's demos (and future F3DEX3 games) on GLideN64. Thank you so much for doing this!

2024-06-12 13:44 UTC, ariahiro64 commented
dev of the only released romhack with f3dex3 support it works reasonably well. 
![image](https://github.com/gonetz/GLideN64/assets/45049787/203d5181-69f1-4750-9546-4bb1f00b2553)

2024-06-30 05:19 UTC, gonetz requested changes
Well done!
I have just a few minor notices.

2024-06-30 05:19 UTC, gonetz commented on src/GBI.cpp
> +				// It will look like F3DEX3_LVP_BrW_NOC
// It will look like F3DEX3_LVP_BrZ_NOC

2024-06-30 05:19 UTC, gonetz commented on src/GBI.cpp
> +			current.f3dex3.branchOnZ = features.find("BrZ") != features.end();
A nitpick: may be use case-insensitive compare there?

2024-06-30 05:20 UTC, gonetz commented
> dev of the only released romhack with f3dex3 support it works reasonably well.

Where can I get that romhack?

2024-06-30 05:25 UTC, ariahiro64 commented
> > dev of the only released romhack with f3dex3 support it works reasonably well.
> 
> Where can I get that romhack?

an old as version was released for the oot hacking contest in hylian modding but if you want a build that isnt ancient i can dm it in discord. i just dont want to have a incomplete version leaking early (after final i dont care if every single build gets pushed to public)

2024-06-30 05:32 UTC, ariahiro64 commented
> > > dev of the only released romhack with f3dex3 support it works reasonably well.
> > 
> > 
> > Where can I get that romhack?
> 
> an old as version was released for the oot hacking contest in hylian modding but if you want a build that isnt ancient i can dm it in discord. i just dont want to have a incomplete version leaking early (after final i dont care if every single build gets pushed to public)

i meant i can give you a newer debug build

2024-06-30 07:35 UTC, aglab2 commented
Addressed various issues in commit https://github.com/gonetz/GLideN64/pull/2842/commits/fc9589b94686f67189c2b0d7fc52b83202d92629

2024-06-30 15:23 UTC, gonetz approved these changes
LGTM!

2024-06-30 15:25 UTC, merged

2024-06-30 15:58 UTC, gonetz commented
> an old as version was released for the oot hacking contest in hylian modding but if you want a build that isnt ancient i can dm it in discord.

@ariahiro64, I sent you a message in discord.